server:
  port: 8083
cors:
<<<<<<< HEAD
  originPatterns: http://localhost:3000,http://localhost:80,https://erosao.com.br
file:
  upload-dir: /Downloads/UploadDir
security:
  jwt:
    token:
      secret-key: =========================wos-spring-boot====================================
=======
  originPatterns: http://localhost:3000,http://localhost:8080,https://erosao.com.br
security:  
  jwt:    
    token:
      secret-key: ======================Woshington=Spring===========================
>>>>>>> 8819ad3b36b9901f1fe538e1d75aecbe46177713
      expire-length: 3600000
      cookieName: cookie
spring:
  datasource:    
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest?useTimezone=true&serverTimezone=UTC
    username: root
    password: Skymysql1!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false 
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /auth/** 
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
logging.level.org.springframework.web: DEBUG

        
