name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:    
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./06_ParametersAndExceptionsHandlers/rest-with-spring-boot-and-java-erudio
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./06_ParametersAndExceptionsHandlers
      run: docker-compose build
    
    - name: Push to docker Hub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
      
